-- MySQL Script generated by MySQL Workbench
-- Tue Jul 21 13:58:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `#__com_sjarchive_issue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_issue` ;

CREATE TABLE IF NOT EXISTS `#__sjarchive_issue` (
  `issue_id` INT(11) NOT NULL AUTO_INCREMENT,
  `num` TINYINT(4) NOT NULL,
  `volume` TINYINT(4) NULL DEFAULT '0',
  `part` TINYINT(4) NULL DEFAULT '0',
  `year` YEAR(4) NOT NULL,
  `special` TINYINT(1) NOT NULL DEFAULT '0',
  `special_comment` VARCHAR(45) NULL DEFAULT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `use_content` TINYINT(1) NOT NULL DEFAULT '0',
  `pdf` VARCHAR(255) NULL DEFAULT NULL,
  `published` TINYINT(1) NOT NULL DEFAULT '1',
  `use_pdf` TINYINT(1) NOT NULL DEFAULT '0',
  `pub_date` DATE NOT NULL,
  `hits` INT(11) NOT NULL DEFAULT '0',
  `params` TEXT NULL DEFAULT NULL,
  `created_date` DATETIME NOT NULL,
  `edit_date` DATETIME NULL DEFAULT NULL,
  `doi` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`issue_id`),
  UNIQUE INDEX `index2` (`num` ASC, `volume` ASC, `part` ASC, `year` ASC, `special` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 527
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `#__sjarchive_article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_article` ;

CREATE TABLE IF NOT EXISTS `#__sjarchive_article` (
  `article_id` INT(11) NOT NULL AUTO_INCREMENT,
  `issue_id` INT(11) NOT NULL,
  `art_type` VARCHAR(3) NOT NULL,
  `position` INT(4) NOT NULL,
  `udk` VARCHAR(45) NULL DEFAULT NULL,
  `pages` VARCHAR(10) NOT NULL,
  `pdf` VARCHAR(255) NOT NULL,
  `hits` INT(11) NULL DEFAULT '0',
  `published` TINYINT(4) NULL DEFAULT '1',
  `translation` VARCHAR(12) NOT NULL DEFAULT '0',
  `submited_date` DATETIME NULL DEFAULT NULL,
  `edited_date` DATETIME NULL DEFAULT NULL,
  `published_date` DATETIME NULL DEFAULT NULL,
  `doi` VARCHAR(50) NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT NULL,
  `edit_date` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`article_id`),
  UNIQUE INDEX `index4` (`issue_id` ASC, `pages` ASC),
  INDEX `issue_idx` (`issue_id` ASC),
  CONSTRAINT `issue`
    FOREIGN KEY (`issue_id`)
    REFERENCES `#__sjarchive_issue` (`issue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2484
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `#__sjarchive_author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_author` ;

CREATE TABLE IF NOT EXISTS `#__sjarchive_author` (
  `author_id` INT(11) NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `ORCID` VARCHAR(20) NULL DEFAULT NULL,
  `scopus_id` VARCHAR(11) NULL DEFAULT NULL,
  `spin_code` VARCHAR(15) NULL DEFAULT NULL,
  `wos_id` VARCHAR(15) NULL DEFAULT NULL,
  `elibrary_id` VARCHAR(10) NULL DEFAULT NULL,
  `scholar_id` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`author_id`),
  UNIQUE INDEX `index2` (`surname`(50) ASC, `firstname`(50) ASC, `email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10134
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `#__sjarchive_article_author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_article_author` ;

CREATE TABLE IF NOT EXISTS `#__sjarchive_article_author` (
  `article_author_id` INT(11) NOT NULL AUTO_INCREMENT,
  `article_id` INT(11) NOT NULL,
  `author_id` INT(11) NOT NULL,
  `author_position` INT(11) NULL DEFAULT NULL,
  `other` TEXT NULL DEFAULT NULL,
  `org` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `language` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`article_author_id`),
  UNIQUE INDEX `index4` (`article_id` ASC, `author_id` ASC),
  UNIQUE INDEX `article_id` (`article_id` ASC, `author_id` ASC, `author_position` ASC),
  INDEX `fk_article_author_1_idx` (`article_id` ASC),
  INDEX `fk_article_author_2_idx` (`author_id` ASC),
  CONSTRAINT `article_author`
    FOREIGN KEY (`article_id`)
    REFERENCES `#__sjarchive_article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `author_article`
    FOREIGN KEY (`author_id`)
    REFERENCES `#__sjarchive_author` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10079
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `#__sjarchive_keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_keyword` ;

CREATE TABLE IF NOT EXISTS `#__sjarchive_keyword` (
  `keyword_id` INT(11) NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`keyword_id`),
  UNIQUE INDEX `index2` (`keyword` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 38832
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `#__sjarchive_article_keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_article_keyword` ;

CREATE TABLE IF NOT EXISTS `#__sjarchive_article_keyword` (
  `keyword_link_id` INT(11) NOT NULL AUTO_INCREMENT,
  `keyword_id` INT(11) NOT NULL,
  `article_id` INT(11) NOT NULL,
  `language` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`keyword_link_id`),
  UNIQUE INDEX `index2` (`keyword_id` ASC, `article_id` ASC),
  INDEX `article_keyword` (`article_id` ASC),
  CONSTRAINT `article_keyword`
    FOREIGN KEY (`article_id`)
    REFERENCES `#__sjarchive_article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `keyword`
    FOREIGN KEY (`keyword_id`)
    REFERENCES `#__sjarchive_keyword` (`keyword_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 38840
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `#__sjarchive_article_review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_article_review` ;

CREATE TABLE IF NOT EXISTS `#__sjarchive_article_review` (
  `review_id` INT(11) NOT NULL AUTO_INCREMENT,
  `article_id` INT(11) NOT NULL,
  `position` INT(4) NOT NULL DEFAULT '1',
  `pdf` VARCHAR(255) NOT NULL,
  `translation` VARCHAR(255) NOT NULL,
  `published` TINYINT(4) NULL DEFAULT '1',
  PRIMARY KEY (`review_id`),
  INDEX `article_id_idx` (`article_id` ASC),
  CONSTRAINT `article_id`
    FOREIGN KEY (`article_id`)
    REFERENCES `#__sjarchive_article` (`article_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `#__sjarchive_article_statistic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_article_statistic` ;

CREATE TABLE IF NOT EXISTS `#__sjarchive_article_statistic` (
  `article_statistic_id` INT(11) NOT NULL AUTO_INCREMENT,
  `article_id` INT(11) NOT NULL,
  `ip` VARCHAR(15) NOT NULL,
  `date` DATETIME NOT NULL,
  `file` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`article_statistic_id`),
  UNIQUE INDEX `index2` (`article_id` ASC, `date` ASC, `ip` ASC),
  CONSTRAINT `article_statisic`
    FOREIGN KEY (`article_id`)
    REFERENCES `#__sjarchive_article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `#__sjarchive_fulltext`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_fulltext` ;

CREATE TABLE IF NOT EXISTS `#__sjarchive_fulltext` (
  `fulltext_id` INT(11) NOT NULL AUTO_INCREMENT,
  `article_id` INT(11) NOT NULL,
  `fulltext` TEXT NULL DEFAULT NULL,
  `language` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`fulltext_id`),
  UNIQUE INDEX `article_id` (`article_id` ASC, `language` ASC),
  INDEX `article_idx` (`article_id` ASC),
  CONSTRAINT `article_fulltext`
    FOREIGN KEY (`article_id`)
    REFERENCES `#__sjarchive_article` (`article_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1871
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `#__sjarchive_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_meta` ;

CREATE TABLE IF NOT EXISTS `#__sjarchive_meta` (
  `meta_id` INT(11) NOT NULL AUTO_INCREMENT,
  `article_id` INT(11) NULL DEFAULT NULL,
  `language` VARCHAR(7) NULL DEFAULT NULL,
  `title` TEXT NULL DEFAULT NULL,
  `abstract` TEXT NULL DEFAULT NULL,
  `section` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`meta_id`),
  UNIQUE INDEX `article_id` (`article_id` ASC, `language` ASC),
  INDEX `article_idx` (`article_id` ASC),
  CONSTRAINT `article_meta`
    FOREIGN KEY (`article_id`)
    REFERENCES `#__sjarchive_article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4708
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `#__sjarchive_reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_reference` ;

CREATE TABLE IF NOT EXISTS `#__sjarchive_reference` (
  `reference_id` INT(11) NOT NULL AUTO_INCREMENT,
  `article_id` INT(11) NOT NULL,
  `position` INT(11) NOT NULL,
  `reference` TEXT NOT NULL,
  `language` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`reference_id`),
  UNIQUE INDEX `article_id` (`article_id` ASC, `position` ASC, `language` ASC),
  INDEX `reference-article_idx` (`article_id` ASC),
  CONSTRAINT `article_reference`
    FOREIGN KEY (`article_id`)
    REFERENCES `#__sjarchive_article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 45838
DEFAULT CHARACTER SET = utf8;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
