-- MySQL Script generated by MySQL Workbench
-- Thu Aug  2 16:32:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

set foreign_key_checks=0;
-- -----------------------------------------------------
-- Table `#__sjarchive_issue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_issue` ;



-- -----------------------------------------------------
-- Table `#__sjarchive_article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_article` ;

-- -----------------------------------------------------
-- Table `#__sjarchive_author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_author` ;


-- -----------------------------------------------------
-- Table `#__sjarchive_article_author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_article_author` ;



-- -----------------------------------------------------
-- Table `#__sjarchive_keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_keyword` ;



-- -----------------------------------------------------
-- Table `#__sjarchive_article_keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_article_keyword` ;



-- -----------------------------------------------------
-- Table `#__sjarchive_article_statistic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_article_statistic` ;



-- -----------------------------------------------------
-- Table `#__sjarchive_reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_reference` ;




-- -----------------------------------------------------
-- Table `#__sjarchive_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_meta` ;


-- -----------------------------------------------------
-- Table `#__sjarchive_fulltext`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_fulltext` ;

-- -----------------------------------------------------
-- Table `#__sjarchive_article_review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `#__sjarchive_article_review` ;


set foreign_key_checks=1;